/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package springConfTest;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.stereotype.Component;
import springConfTest.enums.EventType;
import springConfTest.loggers.EventLogger;
import springConfTest.pojo.Client;
import springConfTest.pojo.Event;
import springConfTest.springConfigClass.AppConfig;

import java.util.Map;

@Component
public class App {

    private final EventLogger defaultLogger;
    private final Client client;
    private final Map<EventType, EventLogger> loggersMap;

    @Autowired
    public App(@Qualifier(value = "cacheFileEventLogger") EventLogger defaultLogger, Client client, Map<EventType, EventLogger> loggersMap) {
        this.defaultLogger = defaultLogger;
        this.client = client;
        this.loggersMap = loggersMap;
    }

    public static void main(String[] args) {
        AnnotationConfigApplicationContext context = new AnnotationConfigApplicationContext(AppConfig.class);
        App app = context.getBean("app", App.class);

        Event event = context.getBean("event", Event.class);
        event.setMsg("Hello dear mister 1");

        app.eventLogger(EventType.INFO, event);
        app.eventLogger(EventType.ERROR, event);
        app.eventLogger(null, event);

        context.close();
    }

    private void eventLogger(EventType type, Event event){
        EventLogger eventLogger = loggersMap.get(type);
        if (eventLogger == null)
            eventLogger = this.defaultLogger;

        String message = event.getMsg();
        event.setMsg(message.replaceAll(String.valueOf(client.getId()), client.getName() + ", " + client.getGreetimg()));
        eventLogger.logEvent(event);
    }

}