/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package springConfTest;

import org.springframework.context.support.ClassPathXmlApplicationContext;

import java.util.Map;

public class App {

    private final EventLogger defaultLogger;
    private final Client client;
    private final Map<EventType, EventLogger> loggers;

    public App(EventLogger defaultLogger, Client client, Map<EventType, EventLogger> loggers) {
        this.defaultLogger = defaultLogger;
        this.client = client;
        this.loggers = loggers;
    }

    public static void main(String[] args) {
        ClassPathXmlApplicationContext context = new ClassPathXmlApplicationContext("hernya_kakayato_japan.xml");
        App app = context.getBean("app", App.class);

        Event event = context.getBean("event", Event.class);
        event.setMsg("Hello dear mister 1");
        app.eventLogger(EventType.INFO, event);

        app.eventLogger(EventType.ERROR, event);
        app.eventLogger(null, event);

        context.close();
    }

    private void eventLogger(EventType type, Event event){
        EventLogger eventLogger = loggers.get(type);
        if (eventLogger == null)
            eventLogger = this.defaultLogger;

        String message = event.getMsg();
        event.setMsg(message.replaceAll(String.valueOf(client.getId()), client.getName()));
        eventLogger.logEvent(event);
    }
}